version: "3"

services:
  app:
    build:
      context: .
      dockerfile: deployment/Docker/app.Dockerfile
    ports:
      - "8000:8000"
  tests:
    build:
      context: .
      dockerfile: deployment/Docker/test.Dockerfile
    environment:
      - APP_ADDRESS=http://app:8000
    depends_on:
      - app
